export { InterpolOptions } from "./options"
export { Interpol } from "./Interpol"
export { Timeline } from "./Timeline"
export { Ticker } from "./core/Ticker"
export { Power1, Power2, Power3, Power4, Expo, easeAdapter } from "./core/ease"
export { styles } from "./core/styles"
export type { El, InterpolConstruct, PropsValues } from "./core/types"
