export { Interpol } from "./Interpol"
export { Timeline } from "./Timeline"
export { Ticker } from "./core/Ticker"
export { Ease } from "./core/Ease"
export { compute } from "./core/compute"
export type { IInterpolConstruct, IUpdateParams } from "./core/types"
